apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      enableServiceLinks: false
      containers:
        - name: php
          image: rigonlucas/hackaton-fpm:1.0.3-RC
          imagePullPolicy: Always
          env:
            - name: APP_URL
              value: http://192.168.85.2/
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: mariadb
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: laravel
            - name: DB_USERNAME
              value: laraveluser
            - name: DB_PASSWORD
              value: laravelpassword
            - name: QUEUE_CONNECTION
              value: redis
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: code
              mountPath: /code
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "cp -r /var/www/html/. /code" ]
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code
